# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ecc9d50dd31999598fcb1707d2456984db35c1b60047ed7a3a83a9de68d464dcab2c885726b2835327e45d7a1cedbb961868029426b71217123c1bd948a9f5e

test:
  secret_key_base: 251bb2a9ba68163f75afdf722066b29ff07082ab30ee23c7247879d5379c7f91e75eeb9de29d27f4c8794a54ed5f6ab0f6b328a921e88260e3f522409be76ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
